
nombre = input("Ingrese un nombre: ").lower()
print(nombre)
print(" ")
print("Contiene a:", "a" in nombre)
print("Contiene e:", "e" in nombre)
print("Contiene i:", "i" in nombre)
print("Contiene o:", "o" in nombre)
print("Contiene u:", "u" in nombre)
print("")
print(nombre)
print(" ")
nombre = input("Ingrese otro nombre: ").lower()

print("Contiene a:", "a" in nombre)
print("Contiene e:", "e" in nombre)
print("Contiene i:", "i" in nombre)
print("Contiene o:", "o" in nombre)
print("Contiene u:", "u" in nombre)